version: '3.8'

services:
  openms-streamlit-template:
    build:
      context: ./openms-streamlit-template
      dockerfile: Dockerfile_simple
    image: openms_streamlit_template
    container_name: openms-streamlit-template
    restart: always
    ports:
      - 8502:8501 # use different host port (here: 8502) to allow multiple apps running on same server.
    volumes:
      - workspaces-streamlit-template:/app/workspaces-streamlit-template
    command: streamlit run openms-streamlit-template/app.py
  umetaflow:
    build:
      context: ./umetaflow-gui
      dockerfile: Dockerfile
    image: umetaflow_app
    container_name: umetaflow-app
    restart: always
    ports:
      - 8503:8501
    volumes:
      - workspaces-umetaflow-gui:/app/workspaces-umetaflow-gui
    command: streamlit run umetaflow-gui/Home.py
volumes:
  workspaces-streamlit-template:
  workspaces-umetaflow-gui: