version: '3.8'

services:
  openms-streamlit-template:
    build:
      context: ./openms-streamlit-template
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: $GITHUB_TOKEN
    image: openms_streamlit_template
    container_name: openms-streamlit-template
    restart: always
    ports:
      - 28502:8501 # use different host port (here: 28502) to allow multiple apps running on same server.
    volumes:
      - workspaces-streamlit-template:/workspaces-streamlit-template
    command: streamlit run openms-streamlit-template/app.py
  umetaflow:
    build:
      context: ./umetaflow-gui
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: $GITHUB_TOKEN
    image: umetaflow_app
    container_name: umetaflow-app
    restart: always
    ports:
      - 28503:8501 # increment port numbers (here 28503)
    volumes:
      - workspaces-umetaflow-gui:/workspaces-umetaflow-gui
    command: streamlit run umetaflow-gui/Home.py
  nuxl-app:
    build:
      context: ./nuxl-app
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: $GITHUB_TOKEN
    image: nuxl_app
    container_name: nuxl-app
    restart: always
    ports:
      - 28504:8501 # increment port numbers (here 28504)
    volumes:
      - workspaces-nuxl-app:/workspaces-nuxl-app
    command: streamlit run nuxl-app/run.py
  PTMScanner: 
    build: 
      context: ./PTMScanner
      dockerfile: Dockerfile 
      args: 
        GITHUB_TOKEN: $GITHUB_TOKEN
    image: PTMScannerApp
    container_name: PTMScanner
    restart: always
    ports: 
      -  28505:8501 
    volumes:
      - workspaces-PTMScanner:/workspaces-PTMScanner
    command: streamlit run PTMScanner/run.py
  FLASHViewer:
    build:
      context: ./FLASHViewer
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: $GITHUB_TOKEN
    image: flashviewer
    container_name: flashviewer
    restart: always
    ports:
      - 28506:8501 # increment port numbers (here 28506)
    volumes:
      - workspaces-flashviewer:/workspaces-flashviewer
  naseweis:
    build:
      context: ./naseweis
      dockerfile: Dockerfile
      args:
        GITHUB_TOKEN: $GITHUB_TOKEN
    image: naseweis
    container_name: naseweis
    restart: always
    ports:
      - 28507:8501 # increment port numbers (here 28507)
    volumes:
      - workspaces-naseweis:/workspaces-naseweis
volumes:
  workspaces-streamlit-template:
  workspaces-umetaflow-gui:
  workspaces-nuxl-app:
  workspaces-flashviewer:
  workspaces-naseweis:
  workspaces-PTMScanner: 
  
